### ISSUE TITLE
New Screen to generate ethereum key

### ISSUE THREAD

**Issue by sadiabbasi** [Tonomy-Foundation/Tonomy-ID#1002]
Acceptance criteria:

- [ ] We need a new screen if user already signup/login and don't have ethereum key
- [ ] Ask for passphrase as we need passphrase to generate key and then go to sign transaction steps.

As an existing user that already created an account before the EThereum feature was launched
I need to enter my passphrase before I sign an Ethreum transaction
So that my account can be created and i  can sign Ethereum transactions

As an existing user that already created an account before the EThereum feature was launched
I need to enter my passphrase
So I can see my Ethereum account and balance on the User Home Screen

https://www.figma.com/design/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=8584-4310&t=5fytcxW7sb12GtiR-4

**Comment by pavel-tonomy** [comment]
Link to the design screens: https://www.figma.com/design/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=8601-4207&t=GVfcEpNHcjWwsWFm-1
