### ISSUE TITLE
Update the account name and balance design 

### ISSUE THREAD

**Issue by sadiabbasi** [Tonomy-Foundation/Tonomy-ID#1009]
Acceptance criteria:

- [ ] LEOS / $ balance does not fit in screen if large
check the screen here if the balance is large https://discord.com/channels/1029385699071381524/1222202330234093709/1241471581021143040

**Comment by pavel-tonomy** [comment]
https://www.figma.com/design/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=8584%3A4310&t=aFdlrvQKJzvUecyy-1
here's the updated screen
