### ISSUE TITLE
react native KeyManager

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID#101]
**API Design planning**

https://www.notion.so/tonomy-foundation/06205895658344fe88f85d9a3374d22a?v=9ed4e9d0e3b34b01bcb0e8cbbf70a2c2&p=067aefec26e146b4b49f410fb13f3eb1&pm=s

**Definition of done**

- [x] key generation functions working, and using argon2id, and are compatible with the JsKeyManager
- [x] storeKey(), signData() and getKey(), removeKey(), generateRandomPrivateKey() and generatePrivateKeyFromPassword() implemented **(1.)**
- [x] implement test framework that can compile react native
- [x] unit tests for the above 3 functions
- [x] generatePrivateKeyFromPassword() outputs the same private key as the JSKeyManager integration. Replicate the unit test inputs for password and salt, and check the privKey is the same.

**Hints**
1. Use `react-native-keychain` and _maybe_ also `react-native-async-storage` package for storage of keys
2. use a RN argon2 implementation https://www.npmjs.com/search?q=react-native%20argon2

**Comment by Rebal67** [comment]
**problem:**
argon2 isn't compatible with expo.
Solutions:
1- eject to use only react native
2- using EAS https://expo.dev/eas (requires payment)
we Decided on using EAS for the ease of use. for further info over start read readme.MD

**Problem:**
testing native packages like "argon2, async-storage" as expo and react native can't unit test external packages and native packages
**Solutions:**
1- mock the external packages and test the packages manually after compiling the app.
2- write end to end tests and run them in emulator https://docs.expo.dev/build-reference/e2e-tests/

**Problem:**
can't convert hex to string in react native as Textconverter and Buffer don't work.
**Solution**
write a function that decode and encode hex (RNKeymanager)

note: argon2 config must be the same for the integration and RNkeymanager to make sure the keys are the same

**Comment by Rebal67** [comment]
for creating a development build read:
https://docs.expo.dev/development/introduction/
https://blog.chiragsrvstv.dev/install-native-modules-with-expo
