### ISSUE TITLE
Wallet signing flow logic design

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID#1014]
Design
- [ ] on mobile, user is redirected to Tonomy ID and navigated to Transaction Signing flow
- [ ] on desktop, and the phone is connected the show feedback that the user needs to sign the transaction on their phone

NOTE: For after Ethereum implemented
- [ ] **on mobile, if Tonomy ID wallet not installed, then show screen telling user to download wallet (here is the Login screen flow for this https://www.figma.com/design/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=3556-25691&t=eDzOicoQWRDUa1zm-4)
- [ ] **on desktop, and the phone is not connected the show feedback that the user needs to ...

**Comment by pavel-tonomy** [comment]
Desktop: https://www.figma.com/design/Aedi8DrZwwParsirLortGt/Tonomy-Demo-Website?node-id=1732-3638&t=6tfMnMLzFu1f9bBn-1

Mobile: https://www.figma.com/design/Aedi8DrZwwParsirLortGt/Tonomy-Demo-Website?node-id=1732-4744&t=6tfMnMLzFu1f9bBn-1

I don't think we need to do separate flows when the phone is connected or not. We can provide a QR code to scan, that's gonna be enough. What do you think?
