### ISSUE TITLE
Design; Adding basic wallet features to UCW

### ISSUE THREAD

**Issue by pavel-tonomy** [Tonomy-Foundation/Tonomy-ID#1048]

**Comment by pavel-tonomy** [comment]
Sending funds flow: https://www.figma.com/design/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=9027-7309&t=1VANH5JpUfLpM6YY-1

Receiving funds flow: https://www.figma.com/design/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=9028-7685&t=1VANH5JpUfLpM6YY-1

**Comment by theblockstalk** [comment]
see comments here https://www.figma.com/design/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=9187-8333&t=a3IotkDKqiZ4n8EI-4
