### ISSUE TITLE
Modify the ISession abstraction 

### ISSUE THREAD

**Issue by sadiabbasi** [Tonomy-Foundation/Tonomy-ID#1062]
Acceptance criteria:

- [ ] Implement the ISession abstraction interface to accept both the wallet connect and ESR session requests.

https://wharfkit.com/docs/session-kit/session

Hint:
export interface ISession {
    createSession(request: unknown): Promise<void> // Authenticate user with WalletConnect/ESR
    disconnectSession(): Promise<void>;  // Disconnect WalletConnect/ESR session
    createTransactionRequest(request: unknown): Promise<unknown>;    // Create WalletConnect/ESR transaction request
    approveRequest(request: unknown): Promise<void>; // Approve WalletConnect/ESR transaction request
    rejectRequest(request: unknown): Promise<void>; // Reject WalletConnect/ESR transaction request
}

Implementation:
class WalletConnectSession implements ISession {}
class ESRSession implements ISession {}

**Comment by theblockstalk** [comment]
this will also implement this into the transaction sign consent screen
