### ISSUE TITLE
Testnet: United Citizens Wallet Mobile app is not working on IOS and Android

### ISSUE THREAD

**Issue by jekingohel** [Tonomy-Foundation/Tonomy-ID#1069]
steps to replicate the issue

Install the United Citizens Wallet app from the Testflight and Google Play Store

**Login**
1) Click on "Login"
2) Give username then click on "Next"
3) Enter the passphrase Click on "Next"

What do you expect to happen?
After click on "Next" it should go to the next page and login.

What happens
By clicking on "Next" page doesn't go to next page. It become blank white screen.

**Create new Account:** 
1) Click on "Create Account"
2) Give username then click on "Next"
3) Save the passphrase Click on "Next "
4) Enter the confirmed passphrase Click on "Next"
5) Read the Terms&Conditions then click on "Accept"
6) Check the checkbox on the Terms and Conditions page
7) Click on "Accept "and click on the checkbox on I Am Human
8) Give a correct image for Captcha on the Human verification page
9) Click on Create an account

What do you expect to happen?
After click on "Create Account" it should go to the next page.

What happens
By clicking on "Create Account" page doesn't go to next page. It become blank white screen.

Environment: **Testnet**

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHNXQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fde606d9b30b08020a0e0bce6e34f577c7e949ca/RPReplay_Final1722246820.mp4)

**Comment by theblockstalk** [comment]
no longer exists says @jekingohel
