### ISSUE TITLE
Design for Scan QR code cases: wrong QR, or wrong environment

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID#1075]
<img width="1317" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmp1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0d2c6282d89d4fc1088f9bdecce317e2dc33e07f/image.png" alt="image.png" />

Acceptance criteria:

- [ ] designs made for cases
    - [ ] app not found
    - [ ] environment is wrong (using Pangea Testnet for a production QR code)
    - [ ] scan QR from completely different system (e.g. scan a URL of a barcode)

**Comment by pavel-tonomy** [comment]
[Link to Figma](https://www.figma.com/design/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=11174-13678&t=CZO6pHTbNbwQY4jz-1)
