### ISSUE TITLE
Design: Scan QR explainer

### ISSUE THREAD

**Issue by pavel-tonomy** [Tonomy-Foundation/Tonomy-ID#1081]
**User story**
- As a Pangea user, I want to get some information about QR code scanner, so I will learn how to use it.

**Designs**
https://www.figma.com/design/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=9097-6697&t=bCqyLgBbbWh1InJn-1

**Acceptance criteria**
- [ ] The hint with information has been added to the interface

**Notes**
[Approximate appearance](https://images-ext-1.discordapp.net/external/gcuKPKQLeP8ROe8GVLI6EWIN86x9lcOQDb_JWxcJX3w/https/uploads-ssl.webflow.com/623793a2e6f9bd9094c827de/630c56e5cf47ceefa16e28e4_Figma.%2520App%2520walkthrough.webp?format=webp&width=1061&height=671)

**Comment by theblockstalk** [comment]
please update link
