### ISSUE TITLE
Design: app instructions

### ISSUE THREAD

**Issue by pavel-tonomy** [Tonomy-Foundation/Tonomy-ID#1084]
**Designs**
https://www.figma.com/design/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=9320-7822&t=nLX4KxCQVnwjaRng-1

**Comment by pavel-tonomy** [comment]
**User story**
As a Pangea user, I want to know what I can do in this application, so I can use it more thoughtfully

**Designs**
TODO

**Comment by theblockstalk** [comment]
see alternative design proposal and comment

**Comment by theblockstalk** [comment]
just 1 comment left
