### ISSUE TITLE
Blocked and warning transactions on Antelope

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID#1085]
any transactions that target the system contracts should have some kind of block or warning. This needs a small design and then a filter of the transaction in the code.

**Comment by theblockstalk** [comment]
sign transaction screen.
if developer mode turned on --> warning message "This is a dangerous action"
if NOT developer mode turned on --> error message "This is a blocked" and user cannot press "Sign"

**Comment by pavel-tonomy** [comment]
here's the design https://www.figma.com/design/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=9973-7676&t=wO5MFzksTpHCoAdY-1

**Comment by theblockstalk** [comment]
this will happen on any antelope chain, if the smart contract being executed is "eosio" or "tonomy"
