### ISSUE TITLE
Design: Explore tab

### ISSUE THREAD

**Issue by pavel-tonomy** [Tonomy-Foundation/Tonomy-ID#1094]
**Designs:** 
https://www.figma.com/design/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=9187-8548&t=3oNnqTePFfT6mA0P-1

**Comment by theblockstalk** [comment]
has this comment been actioned? https://www.figma.com/design/cvV48t0f7O2znT6QBxK0Zj?node-id=9187-8548#911389214

**Comment by theblockstalk** [comment]
I dont see any changes since our last discussion
