### ISSUE TITLE
App Instruction Steps UI:

### ISSUE THREAD

**Issue by sadiabbasi** [Tonomy-Foundation/Tonomy-ID#1126]
Acceptance criteria:

- [ ] https://www.figma.com/design/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=9320-7822&t=nLX4KxCQVnwjaRng-1
- [ ] Implement UI for the instruction steps
- [ ] SHow steps when user create the new account or the already existing user check the app first time.
- [ ]

**Comment by theblockstalk** [comment]
use app storage with a flag if they have seen the instructions

**Comment by theblockstalk** [comment]
https://github.com/Tonomy-Foundation/Tonomy-ID/blob/development/src/utils/StorageManager/entities/appSettings.ts
