### ISSUE TITLE
Design: Working on the graphics for Pangea

### ISSUE THREAD

**Issue by pavel-tonomy** [Tonomy-Foundation/Tonomy-ID#1138]
**Description**
We need some better graphics for Pangea application. We should show AI generated people using UCW, can be photo or high-fidelity illustration. The images are required for:

- [x] Onboarding [link](https://www.figma.com/design/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=10569-5372&t=QwGf8sSRfEQ6ce3b-1)
- [x] Explore [link](https://www.figma.com/design/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=10455-19666&t=QwGf8sSRfEQ6ce3b-1)
- [x] Citizenship tab [link](https://www.figma.com/design/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=10569-3214&t=QwGf8sSRfEQ6ce3b-1)
- [x] Screenshots [link](https://www.figma.com/design/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=10569-1970&t=QwGf8sSRfEQ6ce3b-1)

**Comment by theblockstalk** [comment]
todo
- [ ] finish screenshots for tablet
- [ ] citizen tab - new graphic (more exciting, more accurate)
- [ ] video in the explore tab (designed but not implemented)

**Comment by theblockstalk** [comment]
citizenship tab graphic moving to https://github.com/Tonomy-Foundation/Tonomy-ID/issues/1261
