### ISSUE TITLE
react native Storage class

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID#114]
Definition of done

- [ ] full implementation of the PersistantStorage class exists in the ID app
- [ ] unit test for storage and retrieve and are passing

Hints

1. Use https://www.npmjs.com/package/react-native-async-storage

No namespace yet.

**Comment by Rebal67** [comment]
fix watchman
`echo 999999 | sudo tee -a /proc/sys/fs/inotify/max_user_watches && echo 999999 | sudo tee -a /proc/sys/fs/inotify/max_queued_events && echo 999999 | sudo tee -a /proc/sys/fs/inotify/max_user_instances && watchman shutdown-server && sudo sysctl -p`
check issue: [https://github.com/facebook/watchman/issues/163](url)
