### ISSUE TITLE
Splash screen new UI modification

### ISSUE THREAD

**Issue by sadiabbasi** [Tonomy-Foundation/Tonomy-ID#1141]
Accptence criteria:

https://www.figma.com/design/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=9609-7563&t=AopMQV3GCkl1ZaL2-4

- [ ] Update the splash screen text and graphics according to latest design

**Comment by theblockstalk** [comment]
use app storage with a flag if they have seen the instructions

**Comment by theblockstalk** [comment]
https://github.com/Tonomy-Foundation/Tonomy-ID/blob/development/src/utils/StorageManager/entities/appSettings.ts
