### ISSUE TITLE
Bug - splash screen has battery / wifi icon in it

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID#1156]
When the splash screen is shown, in the top right you can see the battery and wifi icon in it. It looks like a screenshot and does not look good. We should remove that from the splash screen

![2024-09-18 18 08 20](https://github.com/user-attachments/assets/370dbe24-3b42-4d83-be2c-e3757b3354bd)

**Comment by sadiabbasi** [comment]
fixed in virtual nation PR
