### ISSUE TITLE
Edge cases for signing transaction screen or success screen

### ISSUE THREAD

**Issue by sadiabbasi** [Tonomy-Foundation/Tonomy-ID#1179]
1. if their is contract transaction and their is no transaction fee
2. if their is contract transaction and we are not able to fetch parameter
3. if their is asset transfer and no fee
4.

**Comment by theblockstalk** [comment]
See flow conditions here: https://drive.google.com/file/d/1vEaKBllnh8_6XVVeMLzNi0DNT44QiMaI/view?usp=sharing

See "App flow" tab

**Comment by pavel-tonomy** [comment]
Design: https://www.figma.com/design/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=10455-16006&t=IZVsis6wFF8O5PoR-1
