### ISSUE TITLE
Sign Transaction shows [Object] in transaction detail parameters.

### ISSUE THREAD

**Issue by sadiabbasi** [Tonomy-Foundation/Tonomy-ID#1192]
sign transaction screen for proposal for quest - [Object] should be parsed to string

**Comment by theblockstalk** [comment]
this is when creating a quest proposal on Hypha DAO

**Comment by theblockstalk** [comment]
fixed in https://github.com/Tonomy-Foundation/Tonomy-ID/pull/1202
