### ISSUE TITLE
 Remove the "the Tonomy Foundation has been notified" error popup

### ISSUE THREAD

**Issue by sadiabbasi** [Tonomy-Foundation/Tonomy-ID#1199]
- [ ]  Remove the "the Tonomy Foundation has been notified" and replace with "Please try again and if still facing problems create a support ticket on the Pangea discord"
- [ ]   if any unexpected error occurs then check if the current version of the app is the latest from the App Store. If not then tell the user to update their app - giving them the link to the App Store to update.

**Comment by pavel-tonomy** [comment]
Please try again popup [here](https://www.figma.com/design/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=11101-9177&t=HQPlVW5lSZ8nG6cY-1)

Seems we have everything, let me know if something is still missing

**Comment by pavel-tonomy** [comment]
[Figma link](https://www.figma.com/design/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=11101-9177&t=CZO6pHTbNbwQY4jz-1)
