### ISSUE TITLE
Updated android/iOS icon

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID#1205]
The current app icon does not show the full logo. This task is to design a icon that will show the full Pangea logo.
<img width="359" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBek5OQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--da090acb54101a9d5dcafa86ebaaf00c9e4c7eba/image.png" alt="image.png" />

**Comment by pavel-tonomy** [comment]
[Icons](https://www.figma.com/design/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=11153-4315&t=KYbfLmDDuciwQTvw-1)
