### ISSUE TITLE
Error facing when testing tonomy id staging

### ISSUE THREAD

**Issue by sadiabbasi** [Tonomy-Foundation/Tonomy-ID#1210]
1. When install app and go to onboarding getting error: "useWalletStore() Error clearing wallet state:"
2. When I am on the Explore Page, while clicking the "pitch Decks" link, I get the message "page not found."
3.  While I am scanning  with demo app getting duplicate transaction error.
4. If I stay on the Assets page for more than 1 minute, it throws an error: Unexpected JS Error "{"context: "client"}"
5. While Scanning with React app after scanning click on login Then  on Assets page It throws an error: Unexpected JS Error "{"context: "client"}"

**Comment by vemakoti** [comment]
**Steps  to replicate the issue**

- Install the TestFight   from the app store
- Install the Tonomy ID  staging app and click on open
- Click on "Next"
- Click on Start Testing
- Click on Proceed
- Click on Create Account
- Give a Username and click on "Next"
- Rember the passphrase then Click on "Next"
- Please enter the correct passphrase
- Click on "Next" read the Terms&Conditions then click on "Accept"
- Click on Checkboxes  to receive updates then click on "AAccept"
- Click on the check box on the Human Verification page
- Click on the correct image for Hcaptcha verification and click on verify
- Click on "Create Account" Then Click on ok 
- Then it showed "Welcome to Pangea Virtual Nation, With Username" on Citizenship page
- Click on "Explore" Then Click on "Pitch Decks" about Pangea links


***What do you expect to happen?**
It should be open on the Canava homepage

****What actually happens**
After clicking Pitch Decks it showed an error like page not found

 ****Your environment**
- Operating System: IOS -17.6.1
- Tonomy Id staging -Mobile app
- Tonomy Id Staging version:-0.126.0

https://github.com/user-attachments/assets/b9fdbe03-c16a-4844-bd56-2a92d3f4dcab

**Comment by vemakoti** [comment]
*4.* **If I stay on the Assets page for more than 1 minute, It throws an error: Unexpected JS Error "{Context: "Client"}"**


Steps to replicate the issue

Install the TestFight from the app store
Install the Tonomy ID staging app and click on open
Click on "Next"
Click on Start Testing
Click on Proceed
Click on Create Account
Give a Username and click on "Next"
Rember the passphrase then Click on "Next"
Please enter the correct passphrase
Click on "Next" read the Terms&Conditions then click on "Accept"
Click on Checkboxes to receive updates then click on "Accept"
Click on the check box on the Human Verification page
Click on the correct image for Hcaptcha verification and click on verify
Click on "Create Account" Then Click on ok
Then it showed "Welcome to Pangea Virtual Nation, With Username" on Citizenship page
Click on "Assets" 
**What do you expect to happen?**
Assets home page should be stable 

**What actually happens
 If I leave Assets page for more than 1 minute, It throws an error: Unexpected  JS Error "{"context: "client"}"

**Your environment**

Operating System: IOS -17.6.1
Tonomy Id staging -Mobile app
Tonomy Id Staging version:-0.126.0
 


https://github.com/user-attachments/assets/bd2052eb-6391-4085-b866-2f9ece56a1a8

**Comment by vemakoti** [comment]
**5)** ** While Scanning with wallet Connect after scanning click on login Then  on Assets page It throws an error: Unexpected JS Error "{"context: "client"}"**


**Steps to replicate the issue**

Install the TestFight from the app store
Install the Tonomy ID staging app and click on open
Click on "Next"
Click on Start Testing
Click on Proceed
Click on Create Account
Give a Username and click on "Next"
Remember the passphrase then Click on "Next"
Please enter the correct passphrase
Click on "Next" read the Terms&Conditions then click on "Accept"
Click on Checkboxes to receive updates then click on "AAccept"
Click on the check box on the Human Verification page
Click on the correct image for Hcaptcha verification and click on verify
Click on "Create Account" Then Click on ok
Then it showed "Welcome to Pangea Virtual Nation, With Username" on Citizenship page
Then open URL link  **https://react-app.walletconnect.com/** 
Click on Ethereum Sepolia then click on Connect then Click on New pairing
Click on "Assets"  Then Click on  Scan with Connect your wallet 
Then Click on "Log in " on your mobile React app page

**What do you expect to happen? **
It should  show Asset page without any errors

**What actually happens**
After clicking login, It goes to Asset page and throws an error: Unexpected JS Error "{"context: "client"}"

**Your environment**
TestFlight Version: 3.5.2
Operating System: IOS -17.6.1
Tonomy Id staging -Mobile app
Tonomy Id Staging version:-0.126.0


https://github.com/user-attachments/assets/e42284fc-a68b-44dc-9046-9616c042824c

**Comment by vemakoti** [comment]
I retested with a new version(0.134.0) of Tonomy ID Staging and could not replicate this bug.
