### ISSUE TITLE
 Design: Improvements after usability testing

### ISSUE THREAD

**Issue by pavel-tonomy** [Tonomy-Foundation/Tonomy-ID#1258]
- [x] Show APY with monthly earning + USD amount (only when staked amount is known)
- [x] Show d mmm yyyy format (less confusing for US/other date)
- [x] Show multiplier in green on the locked vesting + average multiplier on total. Vesting does not have APY
- [x] Add explanation for why cannot unstake all. make it clearer. "Coins become unlockable 30 days after they have been staked" in unlockable element. maybe also explanation of why vested coins are locked? "Vested coins are unlockable during their vesting period."
- [x] Missing the popup for when user clicks on vesting allocation: allocation date (e.g. 10 April 2023), amount vested (LEOS), cliff duration (e.g. 6 months), vesting period duration (e.g. 2 years), vesting start date (e.g. 30 March 2024), % unlock at vesting start (e.g. 10%), price multiplier (e.g. 6x)
- [x] Make staked and vested allocation elements on assets details screen clickable
- [x] What is staking/vesting popup? "Vested coins are allocated before a public sale at a discounted price and are locked during a vesting period". "Users can stake coins which locks them for 30 days providing financial security for the network and in return are provided a yield."

[Designs](https://www.figma.com/design/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=11629-8605&t=Y3LcSw4smwFtOzT1-1)

**Comment by theblockstalk** [comment]
- show APY with monthly earning + USD amount (only when staked amount is known)
- show d mmm yyyy format (less confusing for US/other date)
- show multiplier in green on the locked vesting + average multiplier on total. Vesting does not have APY
- explanation for why cannot unstake all. make it clearer. "Coins become unlockable 30 days after they have been staked" in unlockable element. maybe also explanation of why vested coins are locked? "Vested coins are unlockable during their vesting period."
- missing the popup for when user clicks on vesting allocation: allocation date (e.g. 10 April 2023), amount vested (LEOS), cliff duration (e.g. 6 months), vesting period duration (e.g. 2 years), vesting start date (e.g. 30 March 2024), % unlock at vesting start (e.g. 10%)
- make staked and vested allocation elements on assets details screen clickable
- what is staking/vesting popup? "Vested coins are allocated before a public sale at a discounted price and are locked during a vesting period". "Users can stake coins which locks them for 30 days providing financial security for the network and in return are provided a yield."
