### ISSUE TITLE
Unexpected JS Error: updateBalance() Error fetching balance Pangea:

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID#1271]
> Good evening. I have a problem with my Unitied Citizen Wallet. When I open my wallet and log in, I cannot see my purchased Leos. I see the attached error message.

> I closed the app, deleted the app and start again…but still the error message

<img width="368" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2Z3Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0d3da7482d62757534dbfe4c4fd95f175ac25952/image.png" alt="image.png" />

**Comment by sadiabbasi** [comment]
Android:  not able to replicate . in production or also in development.
IOS: able to replicate in production. now trying to replicate in development.

**Comment by vemakoti** [comment]
**Steps to replicate the issue**
1) After Creating an account UCW mobile app/Scan QR  with wallet connet
2) open https://react-app.walletconnect.com/
3) Click on Ethereum Sepolia then click on connect
4) Click on Assets on your mobile UCW app 
5) Then click on Scan Qr on mobile scan with wallet connect
6) Click on login on mobile app
7) eth_sendTranscation on Ethereum Sepolia (Wallet connect)
8) Click on Sign Transaction

**What do you expect to happen?**
Transaction successfully  page is opened without throwing an error


**What happens**
It is showing Transactions  successful with Unexoexted JS Error
<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFAxQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6c638130f3c17ae43532063f7e6ba430dd1363c6/IMG_6440.PNG" alt="IMG_6440.PNG" />
