### ISSUE TITLE
Home - UI

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID#184]
Screen design implemented
https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=1090%3A8919

Definition of done!
- [ ] UI matches Figma design
- [ ] reactive layout is used (position of elements will change depending on screen size)
- [ ] UI uses containers/component abstractions as adequate
- [ ] Theme is used or any non-standard component colors
- [ ] Need Help, T&C, and Privacy Notice links opens link from config file
- [ ] If a user clicks on the Login button they are Navigated to the login screen
- [ ] If a user clicks on the Create account button they are Navigated to the create Account screen

Hint:

* LoginScreen --> LoginContainer ( this will have the login logic)

**Comment by Riae** [comment]
There is no home tab on figma? 
![image_2022-11-07_230459811](https://user-images.githubusercontent.com/34170109/200425247-a3a9c9d1-169b-4459-b511-6f7942c301f6.png)
