### ISSUE TITLE
SSO login website on external site when login button pressed - logic SDK

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID#228]
https://docs.google.com/presentation/d/1xz7jMqM72CSvQBPK03miac0xjLgzyVnSBfjOecxVvwA/edit#slide=id.g17dc3ae99c9_0_0

**Definition of done**

for execution in the external website:
- [ ] New function exists which will create a new random key pair
- [ ] It will then use the private key to sign a random number, the URL, and its public key, Creating a jwt
- [ ] there will then redirect to the id website, With the jwt in the redirect URL

**Comment by theblockstalk** [comment]
input To the function should be a path e.g. `/callback/tonomy` which is the callback URL for the domain. This should also be part of the JWT

**Comment by Rebal67** [comment]
change story points so that it suits for the research and implementing JWK

**Comment by Rebal67** [comment]
https://github.com/decentralized-identity/did-jwt/pull/259
