### ISSUE TITLE
Communication microservice authentication and encryption

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID#234]
We need to implement authentication and encryption for the browser to mobile communication protocol. This should be done using the public-private keys of their account

Authentication could be: DIDComm, VCs, simple challenge request, JWT

Definition of done
this
- [x] Message sent from website to mobile is Authorised by the private key in browser, and encrypted with the public key from the Tonomy ID public key
- [x] messages are sent from Tonomy ID mobile app are authorised with the private key from the mobile app, and encrypted with the public key from the browser

**Comment by theblockstalk** [comment]
check this first:
https://github.com/Tonomy-Foundation/Tonomy-ID-Management/issues/104

**Comment by theblockstalk** [comment]
lets do authentication only for now

**Comment by Rebal67** [comment]
a task needed for writing more integration tests and unit tests

**Comment by Rebal67** [comment]
there is a know bug about the logging into the microservice and expected to be fixed in task #464 
the logging in sometimes doesnt happen correctly or slower then sending a message

**Comment by Rebal67** [comment]
a task need to be added to add the verify guard to the socketGateway in the  communication service: 
- the microserviice now doesn't check if each message is verified and it needs to check it there is an auth guard ready to be used
