### ISSUE TITLE
Fix typescript and enlist errors - ID

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID#264]
Definition of done

- [x] No more reported typescript and eslint errors when `npm run lint` is called (warnings ok)
- [x] Typescript and eslint rules are updated to our best needs
- [x] eslint and typescript disables are added to codebase if needed

https://github.com/Tonomy-Foundation/Tonomy-ID-ID/tree/development
Branch from `development` to branch `feature/264-fix-eslint` and create a PR to show whatever work you do

**Comment by theblockstalk** [comment]
suggested that you allow `any` is changed to a warning, not error code

**Comment by techemmy** [comment]
Okay
