### ISSUE TITLE
SDK dependancy management

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID#281]
The aim of this task is to automate the dependency of the SDK repository. So that new developers do not need to do anything for ID to work instantly.

Ideas for how to do this:

1. add SDK as git submodule of ID, add script in ID folder to automatically setup
  - fix the lsync issue with the SDK unbuilding
  - use metro.config.js to resolve the package (try this first)
2. publish to npmjs with CI pipeline
3. use a git or file reference?

Definition of done

- [x] User can git clone the ID repo And start the expo app in two commands (`npm i` then another e.g. `npm start`)
- [x] README.md is updated with new commands and instructions. Any old content is removed
- [x] Integration repository scripts and README.md are also uppdated

**Comment by Rebal67** [comment]
https://medium.com/@alielmajdaoui/linking-local-packages-in-react-native-the-right-way-2ac6587dcfa2
