### ISSUE TITLE
migrate to latest LTS yarn instead of npm (testing)

### ISSUE THREAD

**Issue by Rebal67** [Tonomy-Foundation/Tonomy-ID#300]
This task is to check that we can upgrade to yarn Successfully, and that all of our existing package installation and linking management mechanisms will still work.

Definition of done:

Install the latest LTS version of yarn as a package manager in

- [ ]  SDK
- [ ]  ID install local + development
- [x]  Demo install local + development

Check all Integration scripts and local commands working

**Comment by kamitor** [comment]
Rebal has done some of this already some of the work.

**Comment by kamitor** [comment]
Check how this is done in the communication microservice repository
