### ISSUE TITLE
Create SSO flow diagram

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID#313]
https://www.notion.so/tonomy-foundation/2022-12-22-Tonomy-ID-retrospectiev-f0f0d8c0e9c24d63a479be79a5631497#46e022d562614b27918381f438c909b3

Definition of done

- [ ] Flow diagram exists that shows the different flows for the single sign-on feature

**Comment by MilicaSequeira** [comment]
need access to it, if possible.

**Comment by theblockstalk** [comment]
https://app.diagrams.net/#G1HkNzDHa3nOc-w9FEthd6e2fHrL11Joff
