### ISSUE TITLE
Design prototype optimizations

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID#315]
Keep the prototype organized, consistent and beautiful
https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=772%3A5523&t=uPKXG0CbK0yJbZpy-0

Definition of done

- [ ] Maintain the design screens in Figma
- [ ] Maintain the prototype linking
- [ ] add to the Design System if needed
- [ ] Keep the frame names consistent
- [ ] Keep a changelog document that developers can review to see what has changed

Review points at the end

**Comment by theblockstalk** [comment]
I have two optimizations already:

1. In many places we have a loading bar (e.g. https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=2117%3A14540&t=uPKXG0CbK0yJbZpy-4) but this only works if we can calculate or estimate how long the operation will take. Better to use a spinner instead when we don't have a time bound.

2. User needs to opt-into having data analytics collected by the app for usability optimization. This should be when the user creates account around where they accept T&Cs and Privacy Policy.

**Comment by MilicaSequeira** [comment]
https://docs.google.com/document/d/1NXds-zIiSuDSX0R4IY5XBifbt0R5D8xMrJYq39ryzW8/edit?usp=sharing

**Comment by theblockstalk** [comment]
https://docs.google.com/spreadsheets/d/1Pr2yxJrdkBvcPUoh9IGMmgeRNXPipm64BkAigovCtBM/edit#gid=0
