### ISSUE TITLE
Setup Jenkins server

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID#36]
Done

- [ ] Jenkins server installed and configured on Digital Ocean server, ready to be used by CI for Tonomy ID

**Comment by kamitor** [comment]
NOW BLOCKED since server is unavailble.

**Comment by kamitor** [comment]
NOW BLOCKED since server is unavailble.

**Comment by theblockstalk** [comment]
@bendre can you create the .md file in the integration repository as discussed, with detailed instructions?

**Comment by kamitor** [comment]
NOW UNBLOCKED
