### ISSUE TITLE
Tonomy App manager - high fidelity designs

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID#360]
**Definition of done**

- [ ] create mockups
- [ ] I fidelity design created

**User stories**

As a Tonomy ID User
I want to create a new app
so that people can log into the app with their Tonomy ID
_App details that are required_
- app name: Market
- username: market
- description: a place to buy all of the NFTs in the world
- logo URL (probably see a preview)
- domain: https://market.com

As an owner oof an App
I want to be able to update some of the details oof the app
so that I can change it if it is needed
_App details that can be updated_
- app name: Market
- username: market
- description: a place to buy all of the NFTs in the world
- logo URL (probably see a preview)
- domain cannot be changed

As an owner of an App
I want to be able to add additional personal information I want from the user during signing
so that when they are logged in I have access to that information
_Personal information that can be requested_
- username

As an owner of an App
I want to be able to delete my App
so that nobody can continue using it to log into my website

**Comment by MilicaSequeira** [comment]
https://www.figma.com/file/7Qg0z3dTuxVtijUdikgEbP/Tonomy-Testing?node-id=262%3A816&t=QmSIg9p4IaSVl604-1

**Comment by MilicaSequeira** [comment]
Untill the review passes correctly, it will stay under another file (not Tonomy ID) and without design system ( in order not to lose time before corrections)
