### ISSUE TITLE
Help chris get access to Telos infrastructure

### ISSUE THREAD

**Issue by kamitor** [Tonomy-Foundation/Tonomy-ID#370]
Chris needs to have a SSH key that doesn't change when he changes computers and location.
Chris swifts location often, and has many computers and laptops that he logs in from.
It is his expierance that his SSH key changes as a result and he doesn't understand how one key will be sufficient.

- [ ]  Chris has an SSH key that he can give to Roger
- [ ]  Chris has check that he has access

**Comment by theblockstalk** [comment]
this is not going to happen
