### ISSUE TITLE
DESIGN - new app creationg  within the App - registering

### ISSUE THREAD

**Issue by kamitor** [Tonomy-Foundation/Tonomy-ID#382]
As a Tonomy ID User or Developer
I want to create a new app
so that people can log into the app with their Tonomy ID
App details that are required

    app name: Market
    username: market
    description: a place to buy all of the NFTs in the world
    logo URL (probably see a preview)
    domain: https://market.com

  app name: Municipality
    username: Engineer 1
    description: a place to see all infrastucture around amsterdam and see outstanding issues.
    logo URL (probably see a preview)
    domain: https://amsterdaminfra.com

CREATE A DESIGN to shows this flow.

**Comment by MilicaSequeira** [comment]
https://www.figma.com/file/7Qg0z3dTuxVtijUdikgEbP/Tonomy-Testing?node-id=262%3A816&t=QmSIg9p4IaSVl604-1

**Comment by MilicaSequeira** [comment]
Untill the review passes correctly, it will stay under another file (not Tonomy ID) and without design system ( in order not to lose time before corrections)
