### ISSUE TITLE
See the link to github and Code; in the design. 

### ISSUE THREAD

**Issue by kamitor** [Tonomy-Foundation/Tonomy-ID#386]
As somebody trying out the SSO Demo
I can get to the Github source code for the page I am looking at 
So I can see what code is running, understand its and understand how to implement it on my own website

Definition of done
- [ ] mockup created for both web and mobile version

**Comment by MilicaSequeira** [comment]
get a github icon that leads to the page with the source code

**Comment by MilicaSequeira** [comment]
https://discordapp.com/channels/1029385699071381524/1039498641968205834/1085188328841822268

**Comment by theblockstalk** [comment]
final work
https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=4394-23181&t=9ldsIeD9hDGktdfh-4
