### ISSUE TITLE
Possibility of information before login to the app _ Transparency 

### ISSUE THREAD

**Issue by kamitor** [Tonomy-Foundation/Tonomy-ID#387]
As somebody trying out the SSO Demo
I can see a concise explanation explaining what is about to happen (before login) or what happened (after login)
so that I can better understand where and how I can use Tonomy ID for my own website

Acceptance criteria

- [x] mockup for the above story is made
- [x] feedback received
- [x] high fidelity design made
- [x] feedback received on high fidelity design
- [ ] feedback implemented in design

**Comment by MilicaSequeira** [comment]
A popup style of window saying what is about to happen, explaining the full process of it. Taking inspo from https://discordapp.com/channels/1029385699071381524/1039498641968205834/1085101581193723977
The point is for devs and non devs alike to know whats up.

**Comment by theblockstalk** [comment]
https://www.loom.com/share/fb362dae921749729dca1d395cd220ed

**Comment by MilicaSequeira** [comment]
https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=4445%3A23188&t=Nzlcp1zZyTKMIsus-1

https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=4495%3A23280&t=Nzlcp1zZyTKMIsus-1

**Comment by theblockstalk** [comment]
@MilicaSequeira and I aligned. This is this work:
https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=4590-23195&t=9ldsIeD9hDGktdfh-4

**Comment by theblockstalk** [comment]
Final work is here
https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=4495-23280&t=9ldsIeD9hDGktdfh-4

Requires refinement task before adding to app
