### ISSUE TITLE
Tonomy Demo: See what's going on with the app AFTER login

### ISSUE THREAD

**Issue by kamitor** [Tonomy-Foundation/Tonomy-ID#388]
As somebody trying out the SSO Demo
I can see what data was exchanged during the login
so that I can better understand where and how to use Tonomy ID for my own website

Acceptance criteria

- [ ] high fidelity design made
- [ ] feedback received on high fidelity design
- [ ] feedback implemented in design

**Comment by MilicaSequeira** [comment]
A popup style of window saying what just happened, explaining the full process of it. Taking inspo from https://discordapp.com/channels/1029385699071381524/1039498641968205834/1085101581193723977
The background window should be blank-is representing any app that enabled tonomy ID sigh in button

**Comment by MilicaSequeira** [comment]
https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=4556%3A23257&t=L0M41A7VhEC9Ig24-1

**Comment by MilicaSequeira** [comment]
the design
https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=4626%3A23356&t=QHLQXWwaJMKDZVjY-1 

how it will be implemented: 
https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=4634%3A25547&t=QHLQXWwaJMKDZVjY-1

or this
https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=4590%3A23195&t=QHLQXWwaJMKDZVjY-1

**Comment by theblockstalk** [comment]
Notes:
- design 2 animation is cooler https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=4590%3A23195&t=QHLQXWwaJMKDZVjY-1
- generally. its very techy and i am not comfortable with it going in the product yet. this is hard work but we'd need to simplify this and make it more visually appealing if we expect even 20% of people to read it
- see comments on the content

**Comment by MilicaSequeira** [comment]
@jack, the link youve added in the comment is from a previous task. Are you saying you prefer the design to be like a chart? Or was it a wrong link you pasted and wanted the comment on on of the 2 possible presentations?

**Comment by MilicaSequeira** [comment]
Finale version:https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=3921%3A22926&t=VCmVHrhkLU4cpS1s-1

**Comment by theblockstalk** [comment]
https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=4590%3A23195&t=ElQJmapxjD7qvf4d-1

**Comment by theblockstalk** [comment]
To avoid confusion, this was the final work.
https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=4590-23195&t=9ldsIeD9hDGktdfh-4

This was deprioritized and before adding to dev epics we should have another design refinement task.
