### ISSUE TITLE
Tonomy Demo: See what's going on before I purchase something - See the signature before I sign it. 

### ISSUE THREAD

**Issue by kamitor** [Tonomy-Foundation/Tonomy-ID#389]
As somebody who has logged in successfully to the SSO Demo (market.com)
I can now try signing a blockchain transaction to buy an NFT with the key that was authorized (And also see the Github code for this - User Story 1)
so that I know that this tool works and how I can implement it

Acceptance criteria

- [ ] high fidelity design made
- [ ] feedback received on high fidelity design
- [ ] feedback implemented in design

**Comment by MilicaSequeira** [comment]
https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=3921%3A22926&t=VCmVHrhkLU4cpS1s-1

**Comment by MilicaSequeira** [comment]
final version https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=3921%3A22926&t=VCmVHrhkLU4cpS1s-1

**Comment by theblockstalk** [comment]
final work
https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=4993-26071&t=9ldsIeD9hDGktdfh-4
