### ISSUE TITLE
Tonomy Demo: See how I can sign a VC in the Demo site

### ISSUE THREAD

**Issue by kamitor** [Tonomy-Foundation/Tonomy-ID#390]
As somebody who has logged in successfully to the SSO Demo (market.com)
I can now try signing a verifiable credential with a medical record in it
so that I know that this tool works and how I can implement it

Acceptance criteria

- [ ] high fidelity design made
- [ ] feedback received on high fidelity design
- [ ] feedback implemented in design

**Comment by theblockstalk** [comment]
low fidelity is here
https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=4877-26347&t=9ldsIeD9hDGktdfh-4

**Comment by MilicaSequeira** [comment]
https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=5114%3A26069&t=2HcOyPf5e8hhiZw7-1
