### ISSUE TITLE
History design update - USERSTORY TO BE MADE

### ISSUE THREAD

**Issue by kamitor** [Tonomy-Foundation/Tonomy-ID#393]
**User story**

As a X
I can Y
So that Z

**API Design planning**

**Definition of done**

- [ ] X
- [ ] Y
- [ ] Z

**Hints**

1.

**Comment by MilicaSequeira** [comment]
https://www.figma.com/file/7Qg0z3dTuxVtijUdikgEbP/Tonomy-Testing?node-id=261%3A816&t=KNt4H40nFWLKxwOd-1
