### ISSUE TITLE
Refactor keymanager

### ISSUE THREAD

**Issue by Rebal67** [Tonomy-Foundation/Tonomy-ID#396]
keymanager must be refactored in the sdk to be an abstract class with the basic usage of all greymass eosio package

- [x]  keymanager becomes an abstract class 
- [x] generatehash from password function must be overriden
- [x] sso website/ demo and id app are extending the keymanager abstract
- [ ]  all greymass functions must come out from sdk
- [x] make default jsKeymanager class that extends the abstract class
- [x] getKey never requires a challenge. requires implementing separate storage for public and private keys
- [x] new function checkKey() to allow to check a challenge is correct
- [x] make sure implementations are checking challenge correctly for signData()

**Comment by theblockstalk** [comment]
let's discuss this before start. I'm starting to see reason to have two separate classes: one to generate keys from password, which only needs to be in TID, and the keyManager which is in all clients. this reduces dependencies on argon2 where it is not necessary, and reduces OOP complexities
