### ISSUE TITLE
PIN challenge - UI

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID#399]
**Definition of done**

- [ ] Design matches Figma screen
https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=807%3A6837&t=sg6kvIIAcJx9Z3VB-4
- [ ] if PIN 5-digits not inputted, NEXT button is disabled
- [ ] reactive layout is used (position of elements will change depending on screen size)
- [ ] UI uses containers/component abstractions as adequate
- [ ] Theme is used or any non-standard component colors

**Comment by HaseebUllahAbbasi** [comment]
on it  @theblockstalk
