### ISSUE TITLE
Run Internal User testing for Tonomy ID

### ISSUE THREAD

**Issue by MilicaSequeira** [Tonomy-Foundation/Tonomy-ID#418]
Book and run internal user testing for the new features done in Tonomy ID ( analytics, history, app) and the new Tonomy App Manager

-  [ ] Talk about the features
- [ ] Gather Feedback
- [ ] and book with each person.

Points allocated PER PERSON.

**Comment by theblockstalk** [comment]
this should be with @alikarani and @bendre first. as the App Manager is for developers

**Comment by kamitor** [comment]
2 point for paticipation
