### ISSUE TITLE
Update app manager based on feedback 

### ISSUE THREAD

**Issue by kamitor** [Tonomy-Foundation/Tonomy-ID#436]
design is updated based on the feedback from task https://github.com/Tonomy-Foundation/Tonomy-ID/issues/433
Acceptance criteria:

- [x] Design is updated baed on feedback listed HERE:

1.Make the listed data more visible
2.See alternative path to edit mode- 2 participant went into burger menu first
3.Label steps with that they are in creating an app
4.Make going back through steps possible
5.Add a plus on home screen so use doesnt need to scroll to end list to get to register an app
6.Get a deafult image to replace a deleted logo
7.In home page show logo of the app with its details
8.Change delete button color to something less clickable
9. Shorten space in the delete popup

**Comment by kamitor** [comment]
Vote afterwards

**Comment by theblockstalk** [comment]
@MilicaSequeira or @kamitor where is this feedback? task is currently not ready

**Comment by MilicaSequeira** [comment]
Its not done. I need to do internal testing before doing this task.

**Comment by MilicaSequeira** [comment]
https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=772%3A5523&t=W4uQgEuLKp2n4YQH-1
