### ISSUE TITLE
Test the acceptance criteria for creating an account

### ISSUE THREAD

**Issue by kamitor** [Tonomy-Foundation/Tonomy-ID#440]
Output: 

DoD: 
- [ ]  Create account flow **on staging** is checked against the acceptance criteria 
- [ ] Any bugs found are added to Github, even if it is not part of the acceptance criteria
- add to the epic
- add to sprint backlog
- [ ] If acceptance criteria is not passed then we comment (in this github issue)

Testing procedure: https://www.notion.so/tonomy-foundation/Tonomy-ID-Testing-Procedure-4a084f9e43df413695425289ca017446

**Comment by sadiabbasi** [comment]
https://github.com/Tonomy-Foundation/Tonomy-ID/issues/543
https://github.com/Tonomy-Foundation/Tonomy-ID/issues/542
https://github.com/Tonomy-Foundation/Tonomy-ID/issues/541

Not able to test the point which we need to check after login as i was not able to login..
