### ISSUE TITLE
User is sent to the user home screen even if the close the app (if user is logged in)

### ISSUE THREAD

**Issue by Rebal67** [Tonomy-Foundation/Tonomy-ID#444]
whenever the user opens and closes the app the user should be checked if loggedin and sent to the right page

- [x]  if user is loggedIn it is pointed to the right navigation which is userHome.
- [x] if user is not loggedIn it is pointed to login register screen
- [x] loggedIn user should not be able to navigate to login and register screens

**Comment by theblockstalk** [comment]
@Rebal67 or @theblockstalk to finish this. See @HaseebUllahAbbasi existing PR first
