### ISSUE TITLE
Keys invalid - User Logged out. 

### ISSUE THREAD

**Issue by kamitor** [Tonomy-Foundation/Tonomy-ID#445]
When the user is Logged into another device
the user get a popup deplaying both cases seperately

((needs user testing))

DoD : 

- [ ] When the Users opens the App, we Check if the user has an account in storage. If not, we send them to the user home Screen.
- [ ] When the User opens the App, we check the Keys of the account are still valid | 
- [ ] IF the user object excist and the Keys are valid, We send them to the USER home screen.
- [ ] If the Keys are not valid, and they are are shown in Popup Then they show that they have logged into another device; For security reasons, we only allow one device to be logged into Tonomy ID at a time.  
- [ ] If the user is logged out, or the keys are invalid we send the user to the home screen and delete any data in the user class and persistant storage related to the user.

**Comment by theblockstalk** [comment]
checkKeysStillValid()
https://github.com/Tonomy-Foundation/Tonomy-ID-SDK/blob/development/src/user.ts#L287
