### ISSUE TITLE
Checks User registration steps

### ISSUE THREAD

**Issue by kamitor** [Tonomy-Foundation/Tonomy-ID#446]
Checks if the user has completed all the user OPTIONAL registration steps 
which are:

- PIN
- Biometric

Case: when you open the app and the close it again, during account creation or login
Value: User can recover last steps when they havn't completed the creating account steps.

DoD:
- [x] new status in persistent storage is created when app starts for first time
status: not logged in, creating account, logging in, logged in
- [x] status is updated based on where the user is in creating account / logging in
- [x] When status === creating an account or logging, If the users finishes the PIN step, then a Flag is set in persistant storage that they have completed the PIN step;
- [x] When status === creating an account or logging, If the users finishes the BIOmetric step, then a Flag is set in persistant storage that they have completed the BioMetric step;
- [x] When the user opens the app THEN Check if the status === creating an account or logging in, and if so take them to the next step they have not finished in those steps
   - [x] if the user has pin flag === false return user to setupPinScreen 
   - [x] if the user has biometic flag === false then return to setupBioMetricsScreen
- [x] When the user has completed the account / login then the pin and biometric flags are deleted.

**Comment by theblockstalk** [comment]
@Rebal67 or @theblockstalk to finish this. See @HaseebUllahAbbasi existing PR first

**Comment by theblockstalk** [comment]
we decided on a different strategy. closing these task. we will need to create a new task.

the new strategy is to send the user to the login screen if they have not finished their PIN
