### ISSUE TITLE
Test the acceptance criteria for logging into an account

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID#451]
Output: 

DoD: 
- [x]  Login to an account flow **on staging** is checked against the acceptance criteria 
- [x] Any bugs found are added to Github, even if it is not part of the acceptance criteria
- [x] If acceptance criteria is not passed then we comment (in this github issue)

Testing procedure: https://www.notion.so/tonomy-foundation/Tonomy-ID-Testing-Procedure-4a084f9e43df413695425289ca017446

**Comment by kamitor** [comment]
Testing all the intergration test; and see if it works and then report back

**Comment by theblockstalk** [comment]
waiting for fix https://github.com/Tonomy-Foundation/Tonomy-ID/issues/636

**Comment by theblockstalk** [comment]
> After I login, but do not finish the PIN/biometric setup and close the app, then when I open the app again I am taken back to (optionally) finish setting up PIN/biometric

This is not the current behaviour. Instead if the user does not finish PIN/biometric they are logout. This is acceptable
