### ISSUE TITLE
Design changes for changing PIN / Biometric

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID#454]
DOD:

Designs update/added
- [x] show design for Face ID (used for iOS)
- [x] on Settings page (or where approiat)
 If the user already has a PIN/Biometric, they are told they can change/remove it. If they don't have a PIN they are told they can add one
- [x] add PIN/Biometric flow matches the add biometric flow in Create Account
- [x] new view allows user to choose if they want to change (PIN only, not Biometric) or remove (Pin/biometric)
- [x] design new flow for change PIN
- [x] design flow for remove PIN/biometric: PIN/biometric challenge, then option warning then confirmation
- [x] if the user inputs an incorrect password or biometric or PIN they are shown an "incorrect (password)" error
- [x] create a flow that notifies you if you want to login you need to set up a PIN/Biometrics

**Comment by MilicaSequeira** [comment]
Ive done a bit of research regarding the removal of pin/biometrics, they usually ask for a passcode so maybe we should keep the master password as confirmation of identity.
