### ISSUE TITLE
Change RN to use expo (with typescript)

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID#47]
Done

- [x] Expo is used to launch the app instead of react native
- [x] Typescript is installed
- [x] Integration environment runs expo instead of emulator, and the app connects to the local environment

**Comment by theblockstalk** [comment]
@Rebal67 great work. you completed the definition of done. unfortunately we also need to update the README.md file with the new dependencies and instructions to run and test ( if possible). Can you please open a new PR to add this. Also, please use our branch policy to merge to development instead of master. We will merge to master when we give a release.

**Comment by kamitor** [comment]
He opend a expo tool @theblockstalk 
All files are migrated @Rebal67
