### ISSUE TITLE
Make flyer for Tonomy ID + HR

### ISSUE THREAD

**Issue by kamitor** [Tonomy-Foundation/Tonomy-ID#472]
- [ ] Make a flyer for Tonomy ID + HR; 
- [ ] Handover to Mike Chris, Cai and spandana, so they know where to find it.

**Comment by kamitor** [comment]
https://www.canva.com/design/DAFchRs4Onc/iGv65focKGdY9yS0Bfasog/edit?utm_content=DAFchRs4Onc&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by MilicaSequeira** [comment]
It's way too busy. 
This is only a simple issue of hierarchy. Hierarchy tells you where to look. 
The illustrations are as loud as the photoshopped image.  Either find a nonphotoshopped image of people to make it more blended or put the feature illustrations on another page.
The paragraph could be easier to read. The light weight letters for the white background dont work.
Page 2: Remove the illustration in the blue band in the middle of the page as well as the black ribbon thingy. The flyers are suppose to be clean.
The screens of Tonomy dont fit on the mobile frame making the flyer cheap looking. 
Exchange Customisable for your needs to just customisable. Customisable alludes to it being fit to one's needs. Also the other 2 statements are 1 word so this should be as well.
The description text below the Scalable, Privacy and Customisable is too thin, so its hard to read. Increase the weight. The green with the black lettering- How do we do this? Change to How is this done?
The bottom link should be in capital letters and the for more information text should be put together with the link and centered.

**Comment by kamitor** [comment]
Thank you the feedback has been added to an new file for design feedback; https://docs.google.com/spreadsheets/d/1ITomObhhhHkPMFDDZFw5ZGNfDlpKiB7rtOA9QQwQNB0/edit?usp=sharing

**Comment by MilicaSequeira** [comment]
@kamitor, nice job, very organized.
