### ISSUE TITLE
Make Followup Saas Mail Flyer

### ISSUE THREAD

**Issue by kamitor** [Tonomy-Foundation/Tonomy-ID#473]
- [ ] a flyer that clearly lays out the benefits of Tonomy ID again but then with Comperative analysis (use pitch) and the Business model.

- [ ] Handover to Chris, Cai and Mike so they know where to find it.

**Comment by theblockstalk** [comment]
already part of https://github.com/Tonomy-Foundation/Tonomy-ID-Management/issues/144
