### ISSUE TITLE
Agree on file structure for RN

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID#49]
Done

- [ ] research structusre
- [ ] decide on structure together

**Comment by theblockstalk** [comment]
@Rebal67 did you already do this? can you put this in our README.md the article and anything else we decided?

**Comment by Rebal67** [comment]
we decided to do this:
 https://learn.habilelabs.io/best-folder-structure-for-react-native-project-a46405bdba7 
but without the sub-scaling of components
