### ISSUE TITLE
Create staging environment infrastucture

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID#50]
Definition of done:

- [ ] Infrastucture for the Demo app, blockchain node and ID app exists for staging environment (does not run the app yet though, only sets up the server)
- [ ] Full documentation describing every step of how to set up from scratch

**Comment by theblockstalk** [comment]
just discussed with Mauricio. see our plan here https://app.diagrams.net/?src=about#G1m-RPXeA2G6b7npx2ntacCc7ddtJWNgBk

Idea is to set up

- [ ] https://www.proxmox.com is the virtualization software used to create VMs on our machine
- [ ] https://www.pfsense.org server that routes trafic to rest of network based on domain name
- [ ] Change routing so all port 80 and 443 trafic is sent to pfsense (Mauricio needs to do this)
- [ ] Give access to pfsense and proxmox to mauricio and dev team
- [ ] forward trafic to rasberry pie

**Comment by theblockstalk** [comment]
this is getting setup here
https://www.notion.so/tonomy-foundation/Tonomy-server-infrastructure-87bde361d0ea435fa661f36921c99a13

**Comment by theblockstalk** [comment]
8 Gb RAM
4 core
50 Gb Storage

**Comment by theblockstalk** [comment]
now plan is to provision the server in Digital Ocean account

**Comment by kamitor** [comment]
CREATING VIRTUAL MACHINE 
8 Gb RAM
4 core
50 Gb Storage
on local machine
Would cost us 48 $ a month

Testing reduction to
4 Gb RAM
2 core
80 Gb Storage
Would cost us 24$ / month

**Comment by kamitor** [comment]
Installing guests additions
