### ISSUE TITLE
Reach out to new Clients 

### ISSUE THREAD

**Issue by kamitor** [Tonomy-Foundation/Tonomy-ID#500]
Definition of done

Only about the LINKEDIN Campagin witgh the Linkedin Helper
Set out a new campagin and messages and Press Play

For Caihou; He 

- [x] Reach out to 150 connections; 
- [ ] Add proof to the task to complete it.

**Comment by kamitor** [comment]
![Screenshot from 2023-02-24 15-53-10.png](https://images.zenhubusercontent.com/62c6df43e6bcf2300a200098/7c0e24ec-4936-4965-a2f6-0f119bcd3ff8)![Screenshot from 2023-02-27 11-13-01.png](https://images.zenhubusercontent.com/62c6df43e6bcf2300a200098/e4f44bdd-5c28-4088-bfea-0430111f1c40)

**Comment by kamitor** [comment]
over 600 Contact requests: however, not all proofs are there for Chris: Give Chris 10 points for this tasks

**Comment by Caihao013** [comment]
Set a meeting this Wednesday.
