### ISSUE TITLE
Tonomy I.D. For Healthcare

### ISSUE THREAD

**Issue by kamitor** [Tonomy-Foundation/Tonomy-ID#510]
Because Spandana and Cailou were still targeting hospitals; Caihou had a meet with a potential client.

Similar to Task 463

**Comment by kamitor** [comment]
https://www.canva.com/design/DAFbH5-fbz8/A8X3ViRWW5-9P447J7FvwA/edit?utm_content=DAFbH5-fbz8&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton 

https://tonomy-foundation.notion.site/Hosipitals-VP-Medical-Chain-4a7cec2041904eeb81e4aebd4ce1efa1

**Comment by kamitor** [comment]
https://www.canva.com/design/DAFbH5-fbz8/A8X3ViRWW5-9P447J7FvwA/edit

**Comment by Caihao013** [comment]
https://www.canva.com/design/DAFbH5-fbz8/A8X3ViRWW5-9P447J7FvwA/edit 
Edited it to make sure the details look good.
