### ISSUE TITLE
Implementation of the back-button logic in implemented screens

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID#530]
Acceptance criteria

- [x] In all of the currently implemented screens, The back button logic is implemented

See
https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=3287%3A13928&t=rknQ0OJNwIxXfrf4-0
and
https://github.com/Tonomy-Foundation/Tonomy-ID/issues/316#issuecomment-1439757704

**Comment by theblockstalk** [comment]
@MilicaSequeira we need an indication of weather you believe the default back button behaviour is not enough for each screeen

**Comment by MilicaSequeira** [comment]
I dont understand what you mean.
