### ISSUE TITLE
Issue in setup pin number screen with digits

### ISSUE THREAD

**Issue by sadiabbasi** [Tonomy-Foundation/Tonomy-ID#542]
Testing and reporting process: <https://www.notion.so/tonomy-foundation/Tonomy-ID-3960924e3e324c28b5a11ba465c22a99?p=4a084f9e43df413695425289ca017446&showMoveTo=true>

## Steps to replicate the issue

1. I open app for the first time
2. I click through the **three splash screens**
3. I press on "Create Account" button on the **Create account screen**
4. I go to pin setup screen and choose pin number 11223.
5. When i click on 3 it shows me pin 11222 

Recorded video link: https://www.loom.com/share/90416b11487b42bc8356a1d9195c3ca7

## What do you expect to happen?

1. When i select 3 number for setup in it should show me 3 in display field 

## What actually happens

1. when i select 3 number for setup pin it shows 2 instead of 3

## Your environment

- Operating system: Android 10.0
- Tonomy ID version: 0.1.10 (click [here](https://play.google.com/store/apps/details?id=foundation.tonomy.projects.tonomyidstaging) on your phone)

**Comment by HaseebUllahAbbasi** [comment]
@sadiabbasi  this done i guess 
https://github.com/Tonomy-Foundation/Tonomy-ID/pull/518

**Comment by sadiabbasi** [comment]
Haseeb completed this
