### ISSUE TITLE
user.checkPIN()

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID#560]
Acceptance criteria

- [x] new async function checkPin(pin: string) exists on the user class
- [x] integration test checkPin() success and failure cases

Hint
- this should use similar logic to the login() function https://github.com/Tonomy-Foundation/Tonomy-ID-SDK/blob/2d75faf25bc291c4e98f6fa5a0cc2ec68d072548/src/user.ts#L263

**Comment by HaseebUllahAbbasi** [comment]
are you working on this task ? otherwise allow me to finish it thanks
