### ISSUE TITLE
Create 2 designs for the website

### ISSUE THREAD

**Issue by MilicaSequeira** [Tonomy-Foundation/Tonomy-ID#567]
Create 2 designs for the website based on the refrences in the link below:
https://discord.com/channels/1029385699071381524/1039498973708304384/1070284927179948092

DOD

**Comment by theblockstalk** [comment]
done and added to Discord
https://discord.com/channels/1029385699071381524/1039498641968205834/1085101581193723977

**Comment by MilicaSequeira** [comment]
https://media.discordapp.net/attachments/1039498641968205834/1083372049789100072/Frame_12.png
https://media.discordapp.net/attachments/1039498641968205834/1083372411547811860/Frame_10.png
https://media.discordapp.net/attachments/1039498641968205834/1083372411828838512/Frame_13.png
