### ISSUE TITLE
Modal Does not Show Up when Click on link in App

### ISSUE THREAD

**Issue by HaseebUllahAbbasi** [Tonomy-Foundation/Tonomy-ID#585]
Testing and reporting process: <https://www.notion.so/tonomy-foundation/Tonomy-ID-3960924e3e324c28b5a11ba465c22a99?p=4a084f9e43df413695425289ca017446&showMoveTo=true>

"Modal Does not Show Up when Click on link in App"

All the Screen where the Link is Provided 
## Steps to replicate the issue

1. I open app for the first time
2. I click through the **three splash screens**
3. I press on "Link in the Three screens and  rest of the screens with links like mentioned in the pic"

## What do you expect to happen?

1. It should Open the Modal or Navigate through browser 

## What actually happens

1. some time just warning is showed  or some time app throws error 

## Your environment

- Operating system: Android 10.0
- Tonomy ID version: latest 
![ss_3](https://user-images.githubusercontent.com/53255366/226882242-cf79cfba-b4cd-4095-88b3-da4373bb9096.jpeg)
![ss_1](https://user-images.githubusercontent.com/53255366/226882277-0378cb99-c79b-4b7f-8d61-f8aef5bb89dc.jpeg)
![ss_2](https://user-images.githubusercontent.com/53255366/226882255-0e8ee9b5-e3a5-4c2b-94c0-dd46450b0da1.jpeg)

**Comment by theblockstalk** [comment]
related to https://github.com/Tonomy-Foundation/Tonomy-ID/issues/185
