### ISSUE TITLE
Spacing of security messages and buttons UI

### ISSUE THREAD

**Issue by MilicaSequeira** [Tonomy-Foundation/Tonomy-ID#602]
Distance between spacing of security messages and buttons unter the message should be 30 px

**Comment by sadiabbasi** [comment]
@MilicaSequeira can you add screen shot ?

**Comment by MilicaSequeira** [comment]
@sadiabbasi 
here you have the spacing written down for some elements, what Im refering to in this pb is the spacing between the Green security message and the blue NEXT button. 
https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=4669%3A24567&t=rZEB70GJZMvIpxS5-1
