### ISSUE TITLE
Enter PIN and fingerprint message

### ISSUE THREAD

**Issue by MilicaSequeira** [Tonomy-Foundation/Tonomy-ID#613]
When a user logs in, enters username and password and finally gets to the security screens of  PIN and Fingerprint for the moment the screens say-  ADD A PIN and ADD A FINGERPRINT…even  if you already have them set up.
Theres no adding anything. They should say enter. 
We use the term ADD A FINGERPRINT or PIN if its you are CREATING these security measures.
What current text implies is  you ADD security measure even if it exists. 
Compared to (my suggestion) ENTER the existing one. 
The text suggestion in situations when youre entering an existing PIN or PASSWORD is: 
https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=4229%3A23309&t=feVTF4UHiru0RGSe-1

and 
https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=4229%3A23368&t=feVTF4UHiru0RGSe-1
because they use language that doesn’t allude you need to ADD but use existing ones.

**Comment by theblockstalk** [comment]
we will deal with this in the final UI/UX signof of the manage PIN/Biometric feature epic. For now please update the Figma designs with this in mind.
