### ISSUE TITLE
Most of the links are the wrong colour.

### ISSUE THREAD

**Issue by MilicaSequeira** [Tonomy-Foundation/Tonomy-ID#673]
Testing and reporting process: <https://www.notion.so/tonomy-foundation/Tonomy-ID-3960924e3e324c28b5a11ba465c22a99?p=4a084f9e43df413695425289ca017446&showMoveTo=true>

Please replace the example bug report below with the information about your bug

"it doesn't work" is not a bug report!

Be very concise! Say what you did on which screen!

## Steps to replicate the issue

1. Almost all the links are the wrong colour. 

## What do you expect to happen?

1. That they are this colour 67D7ED for terms and services and 4CAF50 for green notification/security messages like in examples given 
https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=772%3A5523&t=q03lDuZFCZuSvrWD-1

## What actually happens
![Screenshot_20230418_121059_Tonomy ID Staging](https://user-images.githubusercontent.com/120083204/232757503-b2f19706-e0bc-4e9f-bb8e-a6a597f846ac.jpg)
![Screenshot_20230418_121406_Tonomy ID Staging](https://user-images.githubusercontent.com/120083204/232757519-c5420da0-dd3b-4916-a45d-15cd29179cef.jpg)

## Your environment

- Operating system: Android 13
- Tonomy ID version: 0.17.2 (click [here](https://play.google.com/store/apps/details?id=foundation.tonomy.projects.tonomyidstaging) on your phone)

**Comment by theblockstalk** [comment]
Please use the Theme for this color, if theme color is not correct please fix it

**Comment by theblockstalk** [comment]
there is a Tonomy component for links. lets use that if we can everywhere
