### ISSUE TITLE
Red colour miss match 

### ISSUE THREAD

**Issue by MilicaSequeira** [Tonomy-Foundation/Tonomy-ID#680]
Testing and reporting process: <https://www.notion.so/tonomy-foundation/Tonomy-ID-3960924e3e324c28b5a11ba465c22a99?p=4a084f9e43df413695425289ca017446&showMoveTo=true>

Please replace the example bug report below with the information about your bug

"it doesn't work" is not a bug report!

Be very concise! Say what you did on which screen!

## Steps to replicate the issue

1. Red colour for Remember your password and border colour dont match figma. it should be FF505F

## What do you expect to happen?

1. https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=2219%3A12615&t=q03lDuZFCZuSvrWD-1

## What actually happens

1. see attached image

## Your environment

- Operating system: Android 13
- Tonomy ID version: 0.17.2 (click [here](https://play.google.com/store/apps/details?id=foundation.tonomy.projects.tonomyidstaging) on your phone)
![Screenshot_20230418_121406_Tonomy ID Staging](https://user-images.githubusercontent.com/120083204/232767666-5303c271-60db-4408-b5a7-e91c52218268.jpg)

**Comment by theblockstalk** [comment]
Please use the Theme for this color, if theme color is not correct please fix it

**Comment by sadiabbasi** [comment]
I checked the error colors coming from theme.colors file and it's same
