### ISSUE TITLE
Password screen 

### ISSUE THREAD

**Issue by MilicaSequeira** [Tonomy-Foundation/Tonomy-ID#683]
Testing and reporting process: <https://www.notion.so/tonomy-foundation/Tonomy-ID-3960924e3e324c28b5a11ba465c22a99?p=4a084f9e43df413695425289ca017446&showMoveTo=true>

Please replace the example bug report below with the information about your bug

"it doesn't work" is not a bug report!

Be very concise! Say what you did on which screen!

## Steps to replicate the issue

1. Create password screen besides border colour issues has:
- not matching corner radius. 
- undertext below the input fields matching in size for REMEMBER YOUR PASSWORD TEXT and PASSWORD CONTAINS WORDS.... - --- 
-  Because the forementioned PASSWORD CONTAINS WORDS.... phrase is too big, the distance between it and confitm password text is not as it should be 16px. It also is incorrect size. 

Recorded video link: (optional - make one with the [Loom app](https://play.google.com/store/apps/details?id=com.loom.android) )

## What do you expect to happen?

1. https://www.figma.com/file/vZDoT2gbhCmax9NuHI6Unw/Sizing?node-id=0%3A1&t=tm8EdSkFYxz7L8qn-1 please follow the sizing guide. If something isnt compréhensive please contact the desinger. 

## What actually happens

1. see the attachment

## Your environment

- Operating system: Android 13
- Tonomy ID version: 0.17.2 (click [here](https://play.google.com/store/apps/details?id=foundation.tonomy.projects.tonomyidstaging) on your phone)
![Screenshot_20230418_121222_Tonomy ID Staging](https://user-images.githubusercontent.com/120083204/232770475-5d8f7733-4bed-4dec-898c-c106c3d3a0c7.jpg)

**Comment by theblockstalk** [comment]
password screen gone
