### ISSUE TITLE
Time the key generation function in nodejs to check security

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID#69]
Definition of done

- [x] the KeyManager generate key from password function is timed with different parameters on different browsers and in nodejs
- [x] a calculation is made based on the password length and on the length of a generic password bank list, to determine the amount of time needed for a malicious and well resourced hacker to crack it password
- [x] based on this, a suggestion for the minimum requirements for passwords is made e.g. lenght, character variety

**Comment by techemmy** [comment]
@theblockstalk, Can you explain more about this? "password function is timed with different parameters on different browsers"

**Comment by theblockstalk** [comment]
@techemmy please talk to me before changing something out of the Icebox.

if you want to do this task, we need to have a call about it. too hard via messages.

**Comment by theblockstalk** [comment]
https://docs.google.com/spreadsheets/d/11X9EJ2EeraJvlpA7_Fz0cYhgpTlVZkbxtQBMEV-UkFc/edit#gid=0

Based on this research I suggest we should:
- use argon2id
- use a memory setting of 4xdefault (4x 16384)
- iterate and use argon2 on it's result 16x
- recommend a password with minimum 12 characters, with 1 lower case, 1 upper case, a number and a letter
- this will give us the property that it would take the RIKEN computer centre 155,000 years to break a password

**Comment by theblockstalk** [comment]
https://learn.microsoft.com/en-us/microsoft-365/admin/misc/password-policy-recommendations?view=o365-worldwide#password-guidelines-for-administrators
https://its.weill.cornell.edu/policies/1115-password-policy-and-guidelines
