### ISSUE TITLE
Password border colour

### ISSUE THREAD

**Issue by MilicaSequeira** [Tonomy-Foundation/Tonomy-ID#709]
## Steps to replicate the issue

1. I click login
2. Enter username then reach enter password screen
3. Click on the input field to fill it and it immediately turns blue.

## What do you expect to happen?

1. I expect to have a grey field all up until I have entered the right amount of caracters and then for it to turn blue. username input field doesnt turn blue once you click to fill it so the password shouldnt either. Blue colour isnt representing input mode but correct length.
## What actually happens

1. The minute I enter to fill the field it turns blue.

## Your environment

- Operating system: Android 13
- Tonomy ID version: 0.22.1 (click [here](https://play.google.com/store/apps/details?id=foundation.tonomy.projects.tonomyidstaging) on your phone)

https://user-images.githubusercontent.com/120083204/235845012-2e6aeb76-c4f3-4671-b5f6-aef2baf287f4.mp4

**Comment by theblockstalk** [comment]
password screen gone
