### ISSUE TITLE
Password- Border radius of 

### ISSUE THREAD

**Issue by MilicaSequeira** [Tonomy-Foundation/Tonomy-ID#712]
## Steps to replicate the issue

1. Border radius of enter password isnt 8 like it should be. its smaller than that

## What do you expect to happen?

1.I expect to see the same radius like in all other input fields

## What actually happens

1. The radius I believe is still from the old desig system

## Your environment

- Operating system: Android 13
- Tonomy ID version: 0.22.1 (click [here](https://play.google.com/store/apps/details?id=foundation.tonomy.projects.tonomyidstaging) on your phone)
![Screenshot_20230503_074204_Tonomy ID Staging](https://user-images.githubusercontent.com/120083204/235848099-21ffa161-5433-4e75-9ff5-969dcab153ca.jpg)

**Comment by theblockstalk** [comment]
password screen gone
