### ISSUE TITLE
New T&Cs page

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID#816]
https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?type=design&node-id=6360-4902&mode=design&t=zz0a4NzWTmj4lQ9J-4

Acceptance criteria

- [x] Design matches figma
- [x] User can expand full T&Cs
- [x] User can accept to move forward
- [x] If user presses decline they get a popup https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?type=design&node-id=6354-4355&mode=design&t=zz0a4NzWTmj4lQ9J-4

**Comment by YAS-SIIN** [comment]
Done.
