### ISSUE TITLE
New Privacy Notice page

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID#817]
https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?type=design&node-id=6292-4792&mode=design&t=Piygd5LZwpYEp0lB-4

Acceptance criteria

- [x] Design matches figma
- [x] User can expand full Privacy Notice
- [x] User can accept to move forward
- [x] user can opt into analytics or email marketing
- [x] If user presses decline they get a popup (@milica to finalize) https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?type=design&node-id=6309-3095&mode=design&t=Piygd5LZwpYEp0lB-4

**Comment by YAS-SIIN** [comment]
Done.
