### ISSUE TITLE
Introduction to the Tonomy Foundation Design for UX/UI Design Newcomer

### ISSUE THREAD

**Issue by MilicaSequeira** [Tonomy-Foundation/Tonomy-ID#834]
- Introduction:

- [ ] Design Language and Guidelines: Understand the company's design language, branding guidelines, and any existing design patterns consistently used throughout the product. This ensures consistency and a seamless user experience. 

Learn the most important files from the Figma’s Tonomy Foundation Folder. At the moment of writing this document, they are: Tonomy ID (most important of all), Accounts Website, Demo Website, Tonomy Developer Console and Tonomy Design System.

- [ ] Current Designs and User Flows: Review existing designs and user flows to familiarise yourself with the current state of the product. Identify strengths, weaknesses, and opportunities for improvement. At the moment of writing this document, they are: Tonomy ID (most important of all), Accounts Website, Demo Website, Tonomy Developer Console and Tonomy Design System.

- [ ] User Research and Insights: Gain insights from user research findings and feedback. Understand user pain points, needs, and preferences to inform your design decisions. And Usability and Analytics Data: Review usability testing results and analytics data to understand how users currently interact with the product. This can help identify areas for optimisation.

The links below are as follows: Early User Research done by Jack Tanner 
https://docs.google.com/spreadsheets/d/1yc2fVjNhmWUCEOUpW3LW3jg7_A-MrLw4x28yoddJuFk/edit?usp=drive_link
2x Usability Research done by the previous designer Milica Sequeira: 
https://drive.google.com/drive/folders/1BgE1yS9rg4-uGDHntvxnyBNFhLwgH50g?usp=drive_link
https://drive.google.com/drive/folders/15N0em0oNiSJt8kqsTnRCGcPz5MgYXQjD?usp=drive_link

- [ ] Previous Design Decisions: Understand the rationale behind past design decisions. This helps you avoid reinventing the wheel and ensures you build upon existing solutions.
Look through the previous designs. They can be located in the file of the design in question. Usually labelled Previous Design yyyy/mm/dd

- [ ] Technical Constraints: Familiarize yourself with any technical limitations or constraints that might impact your design choices. Collaborate with developers to find feasible design solutions.

- [ ] Collaboration and Communication Channels: Learn about the communication and collaboration tools used by the team. Establish clear lines of communication with product managers, developers, and other stakeholders. Discord is your best friend. The Foundation is made up of amicable and nice people. Don’t be afraid to ask questions. Not knowing is okay.

- [ ] User Personas: Understand the target audience and user personas that the existing designs cater to. This helps you align your designs with user needs.

- [ ] Competitor Analysis: Conduct a competitive analysis to understand how the product compares to similar offerings in the market. Identify unique selling points and areas for differentiation.

**Comment by theblockstalk** [comment]
1. where find design and brand guidelines?
2. what are our design audience, priorities, process and philosophy
2. how to use Figma with Tonomy
  - different files, what used for
  - design system
  - how change color scheme in a file
  - how to use a component from design system in a file
  - how to prototype
  - any other figma related stuff?
  - naming conventions for frames
  - prototy
3. usability research is useless without more context
4. looking Through previous designs is to be task you as a general onboarding task
