### ISSUE TITLE
Update the Desing System with the new components

### ISSUE THREAD

**Issue by MilicaSequeira** [Tonomy-Foundation/Tonomy-ID#837]
Update the Desing System with the new components.

Acceptance Criteria:

- [ ] Make sure that all the components used in the Tonomy ID file are made into components in the Global Design System

**Comment by theblockstalk** [comment]
approximately 5 - e.g. dropdowns (nationality)

**Comment by MilicaSequeira** [comment]
I need a revote to 1- I added only 2 things
