### ISSUE TITLE
Unexpected JS Error

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID#872]
Steps to reproduce
1. Delete app storage
2. Open app, go through splash screens
3. Click on "Create new account"
4. Type username "Jack10"

OR
1. Delete app storage
2. Open app, go through splash screens
3. Click on "Login"
4. Type username "Jack9"

Expected behaviour:

- Navigated to the create passphrase screen

Actual behaviour:

- unexpected JS Error ( see screenshot)
- app frezes

Environment:

- Android: 11
- Device: Samsung Galaxy A40
- Tonomy Demo App 0.42.6

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2dVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--663df9f50de54eab5c9a78a0aa5d69215a46bd6c/2023-10-07%2012.06.25.jpg)

**Comment by sadiabbasi** [comment]
reset the blockchain server in digitalOcean:
# To reset
cd Tonomy-ID-Integration
./app.sh stop
git pull
./app.sh gitinit master
./app.sh reset all
./app.sh install
export NODE_ENV=demo
./app.sh init
