### ISSUE TITLE
SSO consent screen next button is not working

### ISSUE THREAD

**Issue by sadiabbasi** [Tonomy-Foundation/Tonomy-ID#888]
Steps to reproduce:

- Open the tonomy demo in mobile browser and click on login with tonomy button.
- It redirects to the consent screen when i click on next button.

Actual output:

- it hang the app and go to tonomy logo screen and also not logged in to demo website

Expected output:

- it logged in to the demo website website and show the user menu and pages

https://github.com/Tonomy-Foundation/Tonomy-ID/blob/ad5f063f710691af82228a9dfa35b805ba1b18fc/src/containers/SSOLoginContainer.tsx#L100

**Comment by theblockstalk** [comment]
this has been fixed in the latest PRs (not sure which)
