### ISSUE TITLE
Install a global state management tool

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID#91]
Definition of done

- [ ] User store can be accessed from any component in the RN app
- [ ] username of the logged in user is available globally
- [ ] function that returns if someone is logged in is available globally

**Hints**

Two options:

- React hooks
- Redux
- maybe another one @Rebal67 knows about

**Comment by Rebal67** [comment]
https://www.reactnativeschool.com/comparing-redux-zustand-and-mobx-state-tree

Zustand for simplicity
