### ISSUE TITLE
Create sign transaction consent screens

### ISSUE THREAD

**Issue by sadiabbasi** [Tonomy-Foundation/Tonomy-ID#929]
Acceptance criteria:

- [ ] Create sign transaction consent screens https://www.figma.com/file/7Qg0z3dTuxVtijUdikgEbP/Tonomy-Developer-Console?type=design&node-id=1477-1550&mode=design&t=Zpw0cCZbeRiLVgjc-4
            - with description
            - with transaction (smart contract + action)

**Comment by theblockstalk** [comment]
https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?type=design&node-id=8309-9874&mode=design&t=D3g8uXOHfLDFOZao-4
