### ISSUE TITLE
Transaction detail screen 

### ISSUE THREAD

**Issue by sadiabbasi** [Tonomy-Foundation/Tonomy-ID#930]
Acceptance criteria:

- [ ] transactions details screen UI. 
- [ ] shows transaction functions and arguments
- [ ] show the network (Pangea, Hedera, WAX etc) based on transaction type

**Comment by theblockstalk** [comment]
https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?type=design&node-id=8309-9971&mode=design&t=D3g8uXOHfLDFOZao-4
