### ISSUE TITLE
Detect new transaction coming

### ISSUE THREAD

**Issue by sadiabbasi** [Tonomy-Foundation/Tonomy-ID#931]
Acceptance Criteria:

- [ ]  Create function which detect when new transaction request is received. Like done here https://github.com/Tonomy-Foundation/Tonomy-ID/blob/development/src/services/CommunicationModule.ts#L54
  - [ ] Check that the sender is the same as the account. Like done here: https://github.com/Tonomy-Foundation/Tonomy-ID/blob/development/src/services/CommunicationModule.ts#L94
  - [ ] displays a Local Push Notification If tonomy id not open, like done here: https://github.com/Tonomy-Foundation/Tonomy-ID/blob/development/src/services/CommunicationModule.ts#L84

- [ ]  If App open redirect to transaction consent screen. like here https://github.com/Tonomy-Foundation/Tonomy-ID/blob/development/src/services/CommunicationModule.ts#L80

**Comment by theblockstalk** [comment]
subscribe with wallet connect: https://walletconnect.gitbook.io/docs/quick-start/wallets/react-native
