### ISSUE TITLE
New account creation issuse in Pangea Testnet mobile app - Captcha issue

### ISSUE THREAD

**Issue by vemakoti** [Tonomy-Foundation/Tonomy-ID#938]
*Steps to replicate the issue*

1. Install the Pangea Testnet app , Click and open
2.  Click on "Create Account" then "Enter a Username."
3.  Remember the  Passphrase in the"Create a passphrase Page " 
4. click the "Next button," and follow the instructions
5. Then, the Terms and Conditions pages opened. Click on the "Accept "button 
6.  Click on the check box " I am human." on the Human Verification page 

* What do you expect to happen?*

 Captcha image /text is shown

*What actually happens*
Process is stuck

*Your environment*

 Pangea Testnet - Mobile app
operating system:- Android 13
Pangea Testnet version:- 0.73.0

**Comment by vemakoti** [comment]
Works as expected

**Comment by jekingohel** [comment]
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUM0QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--670bf8768d4904fcf7a2cda4116104146641ef1e/WhatsApp%20Video%202024-07-02%20at%202.35.56%20PM.mp4)
