### ISSUE TITLE
Show accounts on user home screen: implement logic

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID#987]
Acceptance criteria
- [ ] list the networks that the user has active with: account name, balance in native currency + $ USD
- [ ] if the user logs out and back in the account list should be restored in storage

**Comment by theblockstalk** [comment]
get thhe USD price with https://coinmarketcap.com

**Comment by sadiabbasi** [comment]
did this in 987 task PR that is https://github.com/Tonomy-Foundation/Tonomy-ID/pull/1031
