### ISSUE TITLE
New account creation issuse in United Citizens Wallet - Captcha issue

### ISSUE THREAD

**Issue by vemakoti** [Tonomy-Foundation/Tonomy-ID#995]
## Steps to replicate the issue

1. Install the United Citizens Wallet mobile app from the app store
2. Click on Create Account
3. Give a username on the Create Username page 
4. Remember the passphrase  in the "Create Passphrase"
5. Click on the next button and follow the instructions
6. Then, the terms and conditions page opened. Click on the "Accept" button
7. Click on the check box" I am Human" on the Human Verification Page

## What do you expect to happen?

Captcha image/text is shown

## What happens

The next page is shown without the Captcha image/text is shown

## Your environment

- Operating system: IOS 17.4.1
- United Citizens Wallet -Mobile app
- United Citizens Wallet version 2.0.1

**Comment by theblockstalk** [comment]
Jenkin solved this.
